### ISSUE TITLE
`b` is not recognized, but `b.bat` is.

### ISSUE THREAD

**Issue by MatthijsBlom** [leongrdic/wsl-alias#3] opened 2018-08-19 16:45 UTC
I find myself in the following situation.

```
Microsoft Windows [Version 10.0.17134.165]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\...> b
'b' is not recognized as an internal or external command,
operable program or batch file.

C:\...> b.bat
Welcome to wsl-alias! Put your environment variables in ~/.wsl/env.sh
```

If I move `b.bat` to another directory that is on my path and outside the WSL file system, it _can_ be found using just 'b'.

I already tried reinstalling a few times.

Did I miss something, or is PATHEXT not applicable to WSL directories (anymore)?

**Comment by leongrdic** [comment] 2018-08-19 17:19
I'm aware of this happening and can confirm this wasn't the initial
behavior, which means Microsoft has probably changed the way wsl folders
are scanned/treated when in the environment var PATH.
Until I have more time to investigate this issue, I suggest you use
Powershell which works properly for me (calling aliases without `.bat`
extension)

**Comment by MatthijsBlom** [comment] 2018-08-22 11:28
I have noticed no issues when moving some alias files to another, non-WSL directory. Perhaps the solution is as simple as creating a dedicated directory in the Windows file system instead? [It would appear](https://github.com/Microsoft/WSL/issues/3487#issuecomment-414798834) that this is what Microsoft would advise as well.

**Comment by leongrdic** [comment] 2018-08-22 15:48
> It would appear that this is what Microsoft would advise as well.

Microsoft advises not to create/modify the files in the wsl directory using windows tools and wsl-alias never does that.

> I have noticed no issues when moving some alias files to another, non-WSL directory.

that's right. i might move the alias files to somewhere inside the /mnt/c directory and ask the users to put it into their PATH variable. that would also result in a much shorter path var (e.g. C:/Users/User/.wsl-aliases), which is good.

**Comment by MatthijsBlom** [comment] 2018-08-22 18:23
> Microsoft advises not to create/modify the files in the wsl directory using windows tools

That, indeed, is the part I think they are clear about in [their warning blog post](https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/). I cannot however (with satisfactory certainty) deduce from that blog post what the potential consequences of merely _reading_ a file are.

I do not know what constitutes opening, reading, 'accessing', or executing files; hence my liberal-on-the-cautious-side interpretation of Microsoft's advice.

Moving the alias files to somewhere in /mnt/c would also make it easier for users to safely modify them.

**Comment by leongrdic** [comment] 2018-08-23 11:18
I agree with you. Thanks for your help and activity on this issue!
I'll be adding changing the alias directory on the backlog for the next release of wsl-alias

**Comment by leongrdic** [comment] 2018-09-17 16:48
the new release is out! i'm closing this issue because it no longer exists in the new version of `wsl-alias`.

p.s. i found the root cause of this problem, go check https://github.com/Microsoft/WSL/issues/3487#issuecomment-421995505

**Closed as completed by leongrdic** 2018-09-17 16:48 UTC
